GREETINGS = 'Привет{}. Рады тебя приветствовать в нашем магазине-боте'
ADD_TO_CART = 'Добавить в корзину'


CATEGORIES = 1
CART = 2
SETTINGS = 3
NEWS = 4
PRODUCTS_WITH_DISCOUNTS = 5

START_KB = {
    CATEGORIES: 'Категории',
    CART: 'Корзина',
    SETTINGS: 'Настройки',
    NEWS: 'Новости',
    PRODUCTS_WITH_DISCOUNTS: 'Продукты со скидкой'
}

CATEGORY_TAG = 1
PRODUCT_TAG = 2
PRODUCT_DELETE_TAG = 3
PRODUCT_INCREASE_COUNT = 4
PRODUCT_DECREASE_COUNT = 5
CART_CHECKOUT = 6

CHANGE_SETTINGS_NAME = 7
CHANGE_SETTINGS_NICK = 8
CHANGE_SETTINGS_ADDRESS = 9
CHANGE_SETTINGS_PHONE = 10
CHANGE_SETTINGS_EMAIL = 11
